### ISSUE TITLE
Raw data and preprocessing

### ISSUE THREAD

**Issue by adminmyw** [jaeeolma/tree-detection-evo#2]
How wonderful you are for share this code. it is very sad for no text data. when I preprocessing my data, it only have 62 band, then it said:"ValueError: conflicting sizes for dimension 'band': length 461 on 'wavelength' and length 9 on {'band': 'band', 'y': 'y', 'x': 'x'}", how should I deal with it! thank you very much ! contact me：mywswfu@163.com. THANKS!!!!!

**Comment by adminmyw** [comment]
anyone can help me ?

**Comment by mayrajeo** [comment]
Hi, 

I assume that the error is due to following lines:

```
datapath = Path('../data/tiles/')
tile = 'R14C15'
cube = xr.open_rasterio(datapath/(tile+'.tif'))
cube.coords['wavelength'] = ('band', list(atm_cor_bandwidths) + ['CHM'])
cube = cube.swap_dims({'band': 'wavelength'})
```

If your data contain only 62 bands, then you can't use `atm_cor_bandwidths + ['CHM']` here, as that contains the bandwidth information about data used in our study. You have to replace that with your own information, or just omit that. It is used here in order to have the wavelength data easily available for plotting etc.

**Comment by adminmyw** [comment]
Thank you very much. Please answer another questions. I really need your help！
